//
//  TTConfigDefines.h
//  titto
//
//  Created by Paolo Ladisa on 4/3/13.
//  Copyright (c) 2013 titto. All rights reserved.
//

#ifndef titto_TTConfigDefines_h
#define titto_TTConfigDefines_h

// NON SI CAPISCE UN CAZZO
#define FAVORITE_SHOP @"FAV_SHOP"
#define FAVORITE_SHOP_CITTA @"citta"
#define FAVORITE_SHOP_INDIRIZZO @"indirizzo"
#define FAVORITE_SHOP_ID @"cod_fb"

#define MAP_PINS_CACHE @"MAP_PIN_CACHE"
#define BASE_FEED_URL @"http://www.titto.it/app/loadPage.php?pv="

#define FS_PREFIX_INFO @"FS_VENUE"

#define ANAL_KEY @"UA-22401878-1"

/*
 Facebook Keys
 
 MARTINO GAY
 
 */

#define FACEBOOK_DICTIONARY_KEY         @"FACEBOOK_DICTIONARY_KEY"

#define FACEBOOK_DICTIONARY_NAME        @"FACEBOOK_DICTIONARY_NAME"
#define FACEBOOK_DICTIONARY_SURNAME     @"FACEBOOK_DICTIONARY_SURNAME"
#define FACEBOOK_DICTIONARY_USERID      @"FACEBOOK_DICTIONARY_USERID"
#define FACEBOOK_DICTIONARY_EMAIL       @"FACEBOOK_DICTIONARY_EMAIL"
#define FACEBOOK_DICTIONARY_GENDER      @"FACEBOOK_DICTIONARY_GENDER"
#define FACEBOOK_DICTIONARY_BIRTHDAY    @"FACEBOOK_DICTIONARY_BIRTHDAY"
#define FACEBOOK_DICTIONARY_USERLINK    @"FACEBOOK_DICTIONARY_USERLINK"
#define FACEBOOK_DICTIONARY_USERNAME    @"FACEBOOK_DICTIONARY_USERNAME"

#define FACEBOOK_DICTIONARY_CARDID      @"FACEBOOK_DICTIONARY_CARDID"
#define FACEBOOK_DICTIONARY_SHOPID      @"FACEBOOK_DICTIONARY_SHOPID"
#define FACEBOOK_DICTIONARY_SHOPNAME    @"FACEBOOK_DICTIONARY_SHOPNAME"
#define FACEBOOK_DICTIONARY_SHOPCITY    @"FACEBOOK_DICTIONARY_SHOPCITY"
#define FACEBOOK_DICTIONARY_SHOPADDRESS @"FACEBOOK_DICTIONARY_SHOPADDRESS"

#define FACEBOOK_MILLE_CHIAVI_A_CAZZO_DI_CANE @"SUCA"

#endif
